spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest

# адрес мастера
urlmaster: http://localhost:8080

# exchange, который связан с очредью для наливки
exchange: exchange.name
routingkey: command

# путь к каталогу с файлами
# в файлах лежат список путей файлов filePathId в столбик без знаков препинания
folder: path_folder